 // After manifest generation, emit React barrel index
  const reactIndexPath = path.resolve(__dirname, '../packages/react/src/index.ts');
  const exportsContent = manifest
    .map(({ name, category }) =>
      `export { default as ${name} } from './icons/${category}/${name}';`
    )
    .join('
');
  const indexHeader = `// Auto-generated by generate-icons.js - do not edit
`;
  fs.writeFileSync(reactIndexPath, indexHeader + exportsContent + '
', 'utf8');