// Auto-generated by generate-icons.js script @ 2025-05-02T09:57:02.751Z
export interface IconMeta {
  name: string; // PascalCase component name
  category: string; // Original category folder name
}

export const icons: ReadonlyArray<IconMeta> = [] as const;
