// Auto-generated by generate-icons.js script @ 2025-05-05T13:10:39.203Z
export interface IconMeta {
  name: string;           // PascalCase component name without category prefix (e.g., AlertHexagon)
  category: string;       // Original category folder name (e.g., alerts_feedback)
  fullName: string;       // Full name with category prefix (e.g., AlertsFeedbackAlertHexagon)
  tags?: string[];        // Optional tags for search/filtering
}

export const icons: ReadonlyArray<IconMeta> = [
  {
    "name": "Airqlouds",
    "category": "AQ_Products",
    "fullName": "AqProductsAirqlouds"
  },
  {
    "name": "AlertCircle",
    "category": "alerts",
    "fullName": "AlertsAlertCircle"
  },
  {
    "name": "AlertHexagon",
    "category": "alerts",
    "fullName": "AlertsAlertHexagon"
  },
  {
    "name": "AlertOctagon",
    "category": "alerts",
    "fullName": "AlertsAlertOctagon"
  },
  {
    "name": "AlertSquare",
    "category": "alerts",
    "fullName": "AlertsAlertSquare"
  },
  {
    "name": "AlertTriangle",
    "category": "alerts",
    "fullName": "AlertsAlertTriangle"
  },
  {
    "name": "Annotation",
    "category": "communication",
    "fullName": "CommunicationAnnotation"
  },
  {
    "name": "AnnotationAlert",
    "category": "communication",
    "fullName": "CommunicationAnnotationAlert"
  },
  {
    "name": "AnnotationCheck",
    "category": "communication",
    "fullName": "CommunicationAnnotationCheck"
  },
  {
    "name": "AnnotationDots",
    "category": "communication",
    "fullName": "CommunicationAnnotationDots"
  },
  {
    "name": "AnnotationHeart",
    "category": "communication",
    "fullName": "CommunicationAnnotationHeart"
  },
  {
    "name": "AnnotationInfo",
    "category": "communication",
    "fullName": "CommunicationAnnotationInfo"
  },
  {
    "name": "AnnotationPlus",
    "category": "communication",
    "fullName": "CommunicationAnnotationPlus"
  },
  {
    "name": "AnnotationQuestion",
    "category": "communication",
    "fullName": "CommunicationAnnotationQuestion"
  },
  {
    "name": "AnnotationX",
    "category": "communication",
    "fullName": "CommunicationAnnotationX"
  },
  {
    "name": "Announcement01",
    "category": "alerts",
    "fullName": "AlertsAnnouncement01"
  },
  {
    "name": "Announcement02",
    "category": "alerts",
    "fullName": "AlertsAnnouncement02"
  },
  {
    "name": "Announcement03",
    "category": "alerts",
    "fullName": "AlertsAnnouncement03"
  },
  {
    "name": "ArrowBlockDown",
    "category": "arrows",
    "fullName": "ArrowsArrowBlockDown"
  },
  {
    "name": "ArrowBlockLeft",
    "category": "arrows",
    "fullName": "ArrowsArrowBlockLeft"
  },
  {
    "name": "ArrowBlockRight",
    "category": "arrows",
    "fullName": "ArrowsArrowBlockRight"
  },
  {
    "name": "ArrowBlockUp",
    "category": "arrows",
    "fullName": "ArrowsArrowBlockUp"
  },
  {
    "name": "ArrowCircleBrokenDown",
    "category": "arrows",
    "fullName": "ArrowsArrowCircleBrokenDown"
  },
  {
    "name": "ArrowCircleBrokenDownLeft",
    "category": "arrows",
    "fullName": "ArrowsArrowCircleBrokenDownLeft"
  },
  {
    "name": "ArrowCircleBrokenDownRight",
    "category": "arrows",
    "fullName": "ArrowsArrowCircleBrokenDownRight"
  },
  {
    "name": "ArrowCircleBrokenLeft",
    "category": "arrows",
    "fullName": "ArrowsArrowCircleBrokenLeft"
  },
  {
    "name": "ArrowCircleBrokenRight",
    "category": "arrows",
    "fullName": "ArrowsArrowCircleBrokenRight"
  },
  {
    "name": "ArrowCircleBrokenUp",
    "category": "arrows",
    "fullName": "ArrowsArrowCircleBrokenUp"
  },
  {
    "name": "ArrowCircleBrokenUpLeft",
    "category": "arrows",
    "fullName": "ArrowsArrowCircleBrokenUpLeft"
  },
  {
    "name": "ArrowCircleBrokenUpRight",
    "category": "arrows",
    "fullName": "ArrowsArrowCircleBrokenUpRight"
  },
  {
    "name": "ArrowCircleDown",
    "category": "arrows",
    "fullName": "ArrowsArrowCircleDown"
  },
  {
    "name": "ArrowCircleDownLeft",
    "category": "arrows",
    "fullName": "ArrowsArrowCircleDownLeft"
  },
  {
    "name": "ArrowCircleDownRight",
    "category": "arrows",
    "fullName": "ArrowsArrowCircleDownRight"
  },
  {
    "name": "ArrowCircleLeft",
    "category": "arrows",
    "fullName": "ArrowsArrowCircleLeft"
  },
  {
    "name": "ArrowCircleRight",
    "category": "arrows",
    "fullName": "ArrowsArrowCircleRight"
  },
  {
    "name": "ArrowCircleUp",
    "category": "arrows",
    "fullName": "ArrowsArrowCircleUp"
  },
  {
    "name": "ArrowCircleUpLeft",
    "category": "arrows",
    "fullName": "ArrowsArrowCircleUpLeft"
  },
  {
    "name": "ArrowCircleUpRight",
    "category": "arrows",
    "fullName": "ArrowsArrowCircleUpRight"
  },
  {
    "name": "ArrowDown",
    "category": "arrows",
    "fullName": "ArrowsArrowDown"
  },
  {
    "name": "ArrowDownLeft",
    "category": "arrows",
    "fullName": "ArrowsArrowDownLeft"
  },
  {
    "name": "ArrowDownRight",
    "category": "arrows",
    "fullName": "ArrowsArrowDownRight"
  },
  {
    "name": "ArrowLeft",
    "category": "arrows",
    "fullName": "ArrowsArrowLeft"
  },
  {
    "name": "ArrowNarrowDown",
    "category": "arrows",
    "fullName": "ArrowsArrowNarrowDown"
  },
  {
    "name": "ArrowNarrowDownLeft",
    "category": "arrows",
    "fullName": "ArrowsArrowNarrowDownLeft"
  },
  {
    "name": "ArrowNarrowDownRight",
    "category": "arrows",
    "fullName": "ArrowsArrowNarrowDownRight"
  },
  {
    "name": "ArrowNarrowLeft",
    "category": "arrows",
    "fullName": "ArrowsArrowNarrowLeft"
  },
  {
    "name": "ArrowNarrowRight",
    "category": "arrows",
    "fullName": "ArrowsArrowNarrowRight"
  },
  {
    "name": "ArrowNarrowUp",
    "category": "arrows",
    "fullName": "ArrowsArrowNarrowUp"
  },
  {
    "name": "ArrowNarrowUpLeft",
    "category": "arrows",
    "fullName": "ArrowsArrowNarrowUpLeft"
  },
  {
    "name": "ArrowNarrowUpRight",
    "category": "arrows",
    "fullName": "ArrowsArrowNarrowUpRight"
  },
  {
    "name": "ArrowRight",
    "category": "arrows",
    "fullName": "ArrowsArrowRight"
  },
  {
    "name": "ArrowsDown",
    "category": "arrows",
    "fullName": "ArrowsArrowsDown"
  },
  {
    "name": "ArrowsLeft",
    "category": "arrows",
    "fullName": "ArrowsArrowsLeft"
  },
  {
    "name": "ArrowSquareDown",
    "category": "arrows",
    "fullName": "ArrowsArrowSquareDown"
  },
  {
    "name": "ArrowSquareDownLeft",
    "category": "arrows",
    "fullName": "ArrowsArrowSquareDownLeft"
  },
  {
    "name": "ArrowSquareDownRight",
    "category": "arrows",
    "fullName": "ArrowsArrowSquareDownRight"
  },
  {
    "name": "ArrowSquareLeft",
    "category": "arrows",
    "fullName": "ArrowsArrowSquareLeft"
  },
  {
    "name": "ArrowSquareRight",
    "category": "arrows",
    "fullName": "ArrowsArrowSquareRight"
  },
  {
    "name": "ArrowSquareUp",
    "category": "arrows",
    "fullName": "ArrowsArrowSquareUp"
  },
  {
    "name": "ArrowSquareUpLeft",
    "category": "arrows",
    "fullName": "ArrowsArrowSquareUpLeft"
  },
  {
    "name": "ArrowSquareUpRight",
    "category": "arrows",
    "fullName": "ArrowsArrowSquareUpRight"
  },
  {
    "name": "ArrowsRight",
    "category": "arrows",
    "fullName": "ArrowsArrowsRight"
  },
  {
    "name": "ArrowsTriangle",
    "category": "arrows",
    "fullName": "ArrowsArrowsTriangle"
  },
  {
    "name": "ArrowsUp",
    "category": "arrows",
    "fullName": "ArrowsArrowsUp"
  },
  {
    "name": "ArrowUp",
    "category": "arrows",
    "fullName": "ArrowsArrowUp"
  },
  {
    "name": "ArrowUpLeft",
    "category": "arrows",
    "fullName": "ArrowsArrowUpLeft"
  },
  {
    "name": "ArrowUpRight",
    "category": "arrows",
    "fullName": "ArrowsArrowUpRight"
  },
  {
    "name": "BarChart01",
    "category": "charts",
    "fullName": "ChartsBarChart01"
  },
  {
    "name": "BarChart02",
    "category": "charts",
    "fullName": "ChartsBarChart02"
  },
  {
    "name": "BarChart03",
    "category": "charts",
    "fullName": "ChartsBarChart03"
  },
  {
    "name": "BarChart04",
    "category": "charts",
    "fullName": "ChartsBarChart04"
  },
  {
    "name": "BarChart05",
    "category": "charts",
    "fullName": "ChartsBarChart05"
  },
  {
    "name": "BarChart06",
    "category": "charts",
    "fullName": "ChartsBarChart06"
  },
  {
    "name": "BarChart07",
    "category": "charts",
    "fullName": "ChartsBarChart07"
  },
  {
    "name": "BarChart08",
    "category": "charts",
    "fullName": "ChartsBarChart08"
  },
  {
    "name": "BarChart09",
    "category": "charts",
    "fullName": "ChartsBarChart09"
  },
  {
    "name": "BarChart10",
    "category": "charts",
    "fullName": "ChartsBarChart10"
  },
  {
    "name": "BarChart11",
    "category": "charts",
    "fullName": "ChartsBarChart11"
  },
  {
    "name": "BarChart12",
    "category": "charts",
    "fullName": "ChartsBarChart12"
  },
  {
    "name": "BarChartCircle01",
    "category": "charts",
    "fullName": "ChartsBarChartCircle01"
  },
  {
    "name": "BarChartCircle02",
    "category": "charts",
    "fullName": "ChartsBarChartCircle02"
  },
  {
    "name": "BarChartCircle03",
    "category": "charts",
    "fullName": "ChartsBarChartCircle03"
  },
  {
    "name": "BarChartSquare01",
    "category": "charts",
    "fullName": "ChartsBarChartSquare01"
  },
  {
    "name": "BarChartSquare02",
    "category": "charts",
    "fullName": "ChartsBarChartSquare02"
  },
  {
    "name": "BarChartSquare03",
    "category": "charts",
    "fullName": "ChartsBarChartSquare03"
  },
  {
    "name": "BarChartSquareDown",
    "category": "charts",
    "fullName": "ChartsBarChartSquareDown"
  },
  {
    "name": "BarChartSquareMinus",
    "category": "charts",
    "fullName": "ChartsBarChartSquareMinus"
  },
  {
    "name": "BarChartSquarePlus",
    "category": "charts",
    "fullName": "ChartsBarChartSquarePlus"
  },
  {
    "name": "BarChartSquareUp",
    "category": "charts",
    "fullName": "ChartsBarChartSquareUp"
  },
  {
    "name": "BarLineChart",
    "category": "charts",
    "fullName": "ChartsBarLineChart"
  },
  {
    "name": "Bell01",
    "category": "alerts",
    "fullName": "AlertsBell01"
  },
  {
    "name": "Bell02",
    "category": "alerts",
    "fullName": "AlertsBell02"
  },
  {
    "name": "Bell03",
    "category": "alerts",
    "fullName": "AlertsBell03"
  },
  {
    "name": "Bell04",
    "category": "alerts",
    "fullName": "AlertsBell04"
  },
  {
    "name": "BellMinus",
    "category": "alerts",
    "fullName": "AlertsBellMinus"
  },
  {
    "name": "BellOff01",
    "category": "alerts",
    "fullName": "AlertsBellOff01"
  },
  {
    "name": "BellOff02",
    "category": "alerts",
    "fullName": "AlertsBellOff02"
  },
  {
    "name": "BellOff03",
    "category": "alerts",
    "fullName": "AlertsBellOff03"
  },
  {
    "name": "BellPlus",
    "category": "alerts",
    "fullName": "AlertsBellPlus"
  },
  {
    "name": "BellRinging01",
    "category": "alerts",
    "fullName": "AlertsBellRinging01"
  },
  {
    "name": "BellRinging02",
    "category": "alerts",
    "fullName": "AlertsBellRinging02"
  },
  {
    "name": "BellRinging03",
    "category": "alerts",
    "fullName": "AlertsBellRinging03"
  },
  {
    "name": "BellRinging04",
    "category": "alerts",
    "fullName": "AlertsBellRinging04"
  },
  {
    "name": "Calibration",
    "category": "AQ_Products",
    "fullName": "AqProductsCalibration"
  },
  {
    "name": "ChartBreakoutCircle",
    "category": "charts",
    "fullName": "ChartsChartBreakoutCircle"
  },
  {
    "name": "ChartBreakoutSquare",
    "category": "charts",
    "fullName": "ChartsChartBreakoutSquare"
  },
  {
    "name": "ChevronDown",
    "category": "arrows",
    "fullName": "ArrowsChevronDown"
  },
  {
    "name": "ChevronDownDouble",
    "category": "arrows",
    "fullName": "ArrowsChevronDownDouble"
  },
  {
    "name": "ChevronLeft",
    "category": "arrows",
    "fullName": "ArrowsChevronLeft"
  },
  {
    "name": "ChevronLeftDouble",
    "category": "arrows",
    "fullName": "ArrowsChevronLeftDouble"
  },
  {
    "name": "ChevronRight",
    "category": "arrows",
    "fullName": "ArrowsChevronRight"
  },
  {
    "name": "ChevronRightDouble",
    "category": "arrows",
    "fullName": "ArrowsChevronRightDouble"
  },
  {
    "name": "ChevronSelectorHorizontal",
    "category": "arrows",
    "fullName": "ArrowsChevronSelectorHorizontal"
  },
  {
    "name": "ChevronSelectorVertical",
    "category": "arrows",
    "fullName": "ArrowsChevronSelectorVertical"
  },
  {
    "name": "ChevronUp",
    "category": "arrows",
    "fullName": "ArrowsChevronUp"
  },
  {
    "name": "ChevronUpDouble",
    "category": "arrows",
    "fullName": "ArrowsChevronUpDouble"
  },
  {
    "name": "Collocation",
    "category": "AQ_Products",
    "fullName": "AqProductsCollocation"
  },
  {
    "name": "CornerDownLeft",
    "category": "arrows",
    "fullName": "ArrowsCornerDownLeft"
  },
  {
    "name": "CornerDownRight",
    "category": "arrows",
    "fullName": "ArrowsCornerDownRight"
  },
  {
    "name": "CornerLeftDown",
    "category": "arrows",
    "fullName": "ArrowsCornerLeftDown"
  },
  {
    "name": "CornerLeftUp",
    "category": "arrows",
    "fullName": "ArrowsCornerLeftUp"
  },
  {
    "name": "CornerRightDown",
    "category": "arrows",
    "fullName": "ArrowsCornerRightDown"
  },
  {
    "name": "CornerRightUp",
    "category": "arrows",
    "fullName": "ArrowsCornerRightUp"
  },
  {
    "name": "CornerUpLeft",
    "category": "arrows",
    "fullName": "ArrowsCornerUpLeft"
  },
  {
    "name": "CornerUpRight",
    "category": "arrows",
    "fullName": "ArrowsCornerUpRight"
  },
  {
    "name": "Expand01",
    "category": "arrows",
    "fullName": "ArrowsExpand01"
  },
  {
    "name": "Expand02",
    "category": "arrows",
    "fullName": "ArrowsExpand02"
  },
  {
    "name": "Expand03",
    "category": "arrows",
    "fullName": "ArrowsExpand03"
  },
  {
    "name": "Expand04",
    "category": "arrows",
    "fullName": "ArrowsExpand04"
  },
  {
    "name": "Expand05",
    "category": "arrows",
    "fullName": "ArrowsExpand05"
  },
  {
    "name": "Expand06",
    "category": "arrows",
    "fullName": "ArrowsExpand06"
  },
  {
    "name": "FlipBackward",
    "category": "arrows",
    "fullName": "ArrowsFlipBackward"
  },
  {
    "name": "FlipForward",
    "category": "arrows",
    "fullName": "ArrowsFlipForward"
  },
  {
    "name": "HorizontalBarChart01",
    "category": "charts",
    "fullName": "ChartsHorizontalBarChart01"
  },
  {
    "name": "HorizontalBarChart02",
    "category": "charts",
    "fullName": "ChartsHorizontalBarChart02"
  },
  {
    "name": "HorizontalBarChart03",
    "category": "charts",
    "fullName": "ChartsHorizontalBarChart03"
  },
  {
    "name": "Inbox01",
    "category": "communication",
    "fullName": "CommunicationInbox01"
  },
  {
    "name": "Inbox02",
    "category": "communication",
    "fullName": "CommunicationInbox02"
  },
  {
    "name": "Infinity",
    "category": "arrows",
    "fullName": "ArrowsInfinity"
  },
  {
    "name": "LineChartDown01",
    "category": "charts",
    "fullName": "ChartsLineChartDown01"
  },
  {
    "name": "LineChartDown02",
    "category": "charts",
    "fullName": "ChartsLineChartDown02"
  },
  {
    "name": "LineChartDown03",
    "category": "charts",
    "fullName": "ChartsLineChartDown03"
  },
  {
    "name": "LineChartDown04",
    "category": "charts",
    "fullName": "ChartsLineChartDown04"
  },
  {
    "name": "LineChartDown05",
    "category": "charts",
    "fullName": "ChartsLineChartDown05"
  },
  {
    "name": "LineChartUp01",
    "category": "charts",
    "fullName": "ChartsLineChartUp01"
  },
  {
    "name": "LineChartUp02",
    "category": "charts",
    "fullName": "ChartsLineChartUp02"
  },
  {
    "name": "LineChartUp03",
    "category": "charts",
    "fullName": "ChartsLineChartUp03"
  },
  {
    "name": "LineChartUp04",
    "category": "charts",
    "fullName": "ChartsLineChartUp04"
  },
  {
    "name": "LineChartUp05",
    "category": "charts",
    "fullName": "ChartsLineChartUp05"
  },
  {
    "name": "Mail01",
    "category": "communication",
    "fullName": "CommunicationMail01"
  },
  {
    "name": "Mail02",
    "category": "communication",
    "fullName": "CommunicationMail02"
  },
  {
    "name": "Mail03",
    "category": "communication",
    "fullName": "CommunicationMail03"
  },
  {
    "name": "Mail04",
    "category": "communication",
    "fullName": "CommunicationMail04"
  },
  {
    "name": "Mail05",
    "category": "communication",
    "fullName": "CommunicationMail05"
  },
  {
    "name": "MessageAlertCircle",
    "category": "communication",
    "fullName": "CommunicationMessageAlertCircle"
  },
  {
    "name": "MessageAlertSquare",
    "category": "communication",
    "fullName": "CommunicationMessageAlertSquare"
  },
  {
    "name": "MessageChatCircle",
    "category": "communication",
    "fullName": "CommunicationMessageChatCircle"
  },
  {
    "name": "MessageChatSquare",
    "category": "communication",
    "fullName": "CommunicationMessageChatSquare"
  },
  {
    "name": "MessageCheckCircle",
    "category": "communication",
    "fullName": "CommunicationMessageCheckCircle"
  },
  {
    "name": "MessageCheckSquare",
    "category": "communication",
    "fullName": "CommunicationMessageCheckSquare"
  },
  {
    "name": "MessageCircle01",
    "category": "communication",
    "fullName": "CommunicationMessageCircle01"
  },
  {
    "name": "MessageCircle02",
    "category": "communication",
    "fullName": "CommunicationMessageCircle02"
  },
  {
    "name": "MessageDotsCircle",
    "category": "communication",
    "fullName": "CommunicationMessageDotsCircle"
  },
  {
    "name": "MessageDotsSquare",
    "category": "communication",
    "fullName": "CommunicationMessageDotsSquare"
  },
  {
    "name": "MessageHeartCircle",
    "category": "communication",
    "fullName": "CommunicationMessageHeartCircle"
  },
  {
    "name": "MessageHeartSquare",
    "category": "communication",
    "fullName": "CommunicationMessageHeartSquare"
  },
  {
    "name": "MessageNotificationCircle",
    "category": "communication",
    "fullName": "CommunicationMessageNotificationCircle"
  },
  {
    "name": "MessageNotificationSquare",
    "category": "alerts",
    "fullName": "AlertsMessageNotificationSquare"
  },
  {
    "name": "MessageNotificationSquare",
    "category": "communication",
    "fullName": "CommunicationMessageNotificationSquare"
  },
  {
    "name": "MessagePlusCircle",
    "category": "communication",
    "fullName": "CommunicationMessagePlusCircle"
  },
  {
    "name": "MessagePlusSquare",
    "category": "communication",
    "fullName": "CommunicationMessagePlusSquare"
  },
  {
    "name": "MessageQuestionCircle",
    "category": "communication",
    "fullName": "CommunicationMessageQuestionCircle"
  },
  {
    "name": "MessageQuestionSquare",
    "category": "communication",
    "fullName": "CommunicationMessageQuestionSquare"
  },
  {
    "name": "MessageSmileCircle",
    "category": "communication",
    "fullName": "CommunicationMessageSmileCircle"
  },
  {
    "name": "MessageSmileSquare",
    "category": "communication",
    "fullName": "CommunicationMessageSmileSquare"
  },
  {
    "name": "MessageSquare01",
    "category": "communication",
    "fullName": "CommunicationMessageSquare01"
  },
  {
    "name": "MessageSquare02",
    "category": "communication",
    "fullName": "CommunicationMessageSquare02"
  },
  {
    "name": "MessageTextCircle01",
    "category": "communication",
    "fullName": "CommunicationMessageTextCircle01"
  },
  {
    "name": "MessageTextCircle02",
    "category": "communication",
    "fullName": "CommunicationMessageTextCircle02"
  },
  {
    "name": "MessageTextSquare01",
    "category": "communication",
    "fullName": "CommunicationMessageTextSquare01"
  },
  {
    "name": "MessageTextSquare02",
    "category": "communication",
    "fullName": "CommunicationMessageTextSquare02"
  },
  {
    "name": "MessageXCircle",
    "category": "communication",
    "fullName": "CommunicationMessageXCircle"
  },
  {
    "name": "MessageXSquare",
    "category": "communication",
    "fullName": "CommunicationMessageXSquare"
  },
  {
    "name": "Monitor",
    "category": "AQ_Products",
    "fullName": "AqProductsMonitor"
  },
  {
    "name": "NotificationBox",
    "category": "alerts",
    "fullName": "AlertsNotificationBox"
  },
  {
    "name": "NotificationText",
    "category": "alerts",
    "fullName": "AlertsNotificationText"
  },
  {
    "name": "Phone",
    "category": "communication",
    "fullName": "CommunicationPhone"
  },
  {
    "name": "PhoneCall01",
    "category": "communication",
    "fullName": "CommunicationPhoneCall01"
  },
  {
    "name": "PhoneCall02",
    "category": "communication",
    "fullName": "CommunicationPhoneCall02"
  },
  {
    "name": "PhoneHangUp",
    "category": "communication",
    "fullName": "CommunicationPhoneHangUp"
  },
  {
    "name": "PhoneIncoming01",
    "category": "communication",
    "fullName": "CommunicationPhoneIncoming01"
  },
  {
    "name": "PhoneIncoming02",
    "category": "communication",
    "fullName": "CommunicationPhoneIncoming02"
  },
  {
    "name": "PhoneOutgoing01",
    "category": "communication",
    "fullName": "CommunicationPhoneOutgoing01"
  },
  {
    "name": "PhoneOutgoing02",
    "category": "communication",
    "fullName": "CommunicationPhoneOutgoing02"
  },
  {
    "name": "PhonePause",
    "category": "communication",
    "fullName": "CommunicationPhonePause"
  },
  {
    "name": "PhonePlus",
    "category": "communication",
    "fullName": "CommunicationPhonePlus"
  },
  {
    "name": "PhoneX",
    "category": "communication",
    "fullName": "CommunicationPhoneX"
  },
  {
    "name": "PieChart01",
    "category": "charts",
    "fullName": "ChartsPieChart01"
  },
  {
    "name": "PieChart02",
    "category": "charts",
    "fullName": "ChartsPieChart02"
  },
  {
    "name": "PieChart03",
    "category": "charts",
    "fullName": "ChartsPieChart03"
  },
  {
    "name": "PieChart04",
    "category": "charts",
    "fullName": "ChartsPieChart04"
  },
  {
    "name": "PresentationChart01",
    "category": "charts",
    "fullName": "ChartsPresentationChart01"
  },
  {
    "name": "PresentationChart02",
    "category": "charts",
    "fullName": "ChartsPresentationChart02"
  },
  {
    "name": "PresentationChart03",
    "category": "charts",
    "fullName": "ChartsPresentationChart03"
  },
  {
    "name": "RefreshCcw01",
    "category": "arrows",
    "fullName": "ArrowsRefreshCcw01"
  },
  {
    "name": "RefreshCcw02",
    "category": "arrows",
    "fullName": "ArrowsRefreshCcw02"
  },
  {
    "name": "RefreshCcw03",
    "category": "arrows",
    "fullName": "ArrowsRefreshCcw03"
  },
  {
    "name": "RefreshCcw04",
    "category": "arrows",
    "fullName": "ArrowsRefreshCcw04"
  },
  {
    "name": "RefreshCcw05",
    "category": "arrows",
    "fullName": "ArrowsRefreshCcw05"
  },
  {
    "name": "RefreshCw01",
    "category": "arrows",
    "fullName": "ArrowsRefreshCw01"
  },
  {
    "name": "RefreshCw02",
    "category": "arrows",
    "fullName": "ArrowsRefreshCw02"
  },
  {
    "name": "RefreshCw03",
    "category": "arrows",
    "fullName": "ArrowsRefreshCw03"
  },
  {
    "name": "RefreshCw04",
    "category": "arrows",
    "fullName": "ArrowsRefreshCw04"
  },
  {
    "name": "RefreshCw05",
    "category": "arrows",
    "fullName": "ArrowsRefreshCw05"
  },
  {
    "name": "ReverseLeft",
    "category": "arrows",
    "fullName": "ArrowsReverseLeft"
  },
  {
    "name": "ReverseRight",
    "category": "arrows",
    "fullName": "ArrowsReverseRight"
  },
  {
    "name": "Send01",
    "category": "communication",
    "fullName": "CommunicationSend01"
  },
  {
    "name": "Send02",
    "category": "communication",
    "fullName": "CommunicationSend02"
  },
  {
    "name": "Send03",
    "category": "communication",
    "fullName": "CommunicationSend03"
  },
  {
    "name": "Sites",
    "category": "AQ_Products",
    "fullName": "AqProductsSites"
  },
  {
    "name": "SwitchHorizontal01",
    "category": "arrows",
    "fullName": "ArrowsSwitchHorizontal01"
  },
  {
    "name": "SwitchHorizontal02",
    "category": "arrows",
    "fullName": "ArrowsSwitchHorizontal02"
  },
  {
    "name": "SwitchVertical01",
    "category": "arrows",
    "fullName": "ArrowsSwitchVertical01"
  },
  {
    "name": "SwitchVertical02",
    "category": "arrows",
    "fullName": "ArrowsSwitchVertical02"
  },
  {
    "name": "ThumbsDown",
    "category": "alerts",
    "fullName": "AlertsThumbsDown"
  },
  {
    "name": "ThumbsUp",
    "category": "alerts",
    "fullName": "AlertsThumbsUp"
  },
  {
    "name": "TrendDown01",
    "category": "charts",
    "fullName": "ChartsTrendDown01"
  },
  {
    "name": "TrendDown02",
    "category": "charts",
    "fullName": "ChartsTrendDown02"
  },
  {
    "name": "TrendUp01",
    "category": "charts",
    "fullName": "ChartsTrendUp01"
  },
  {
    "name": "TrendUp02",
    "category": "charts",
    "fullName": "ChartsTrendUp02"
  }
] as const;

// Map for backward compatibility - for each icon, create a mapping from fullName to name
export const iconAliases: Record<string, string> = {
  'AqProductsAirqlouds': 'Airqlouds',
  'AlertsAlertCircle': 'AlertCircle',
  'AlertsAlertHexagon': 'AlertHexagon',
  'AlertsAlertOctagon': 'AlertOctagon',
  'AlertsAlertSquare': 'AlertSquare',
  'AlertsAlertTriangle': 'AlertTriangle',
  'CommunicationAnnotation': 'Annotation',
  'CommunicationAnnotationAlert': 'AnnotationAlert',
  'CommunicationAnnotationCheck': 'AnnotationCheck',
  'CommunicationAnnotationDots': 'AnnotationDots',
  'CommunicationAnnotationHeart': 'AnnotationHeart',
  'CommunicationAnnotationInfo': 'AnnotationInfo',
  'CommunicationAnnotationPlus': 'AnnotationPlus',
  'CommunicationAnnotationQuestion': 'AnnotationQuestion',
  'CommunicationAnnotationX': 'AnnotationX',
  'AlertsAnnouncement01': 'Announcement01',
  'AlertsAnnouncement02': 'Announcement02',
  'AlertsAnnouncement03': 'Announcement03',
  'ArrowsArrowBlockDown': 'ArrowBlockDown',
  'ArrowsArrowBlockLeft': 'ArrowBlockLeft',
  'ArrowsArrowBlockRight': 'ArrowBlockRight',
  'ArrowsArrowBlockUp': 'ArrowBlockUp',
  'ArrowsArrowCircleBrokenDown': 'ArrowCircleBrokenDown',
  'ArrowsArrowCircleBrokenDownLeft': 'ArrowCircleBrokenDownLeft',
  'ArrowsArrowCircleBrokenDownRight': 'ArrowCircleBrokenDownRight',
  'ArrowsArrowCircleBrokenLeft': 'ArrowCircleBrokenLeft',
  'ArrowsArrowCircleBrokenRight': 'ArrowCircleBrokenRight',
  'ArrowsArrowCircleBrokenUp': 'ArrowCircleBrokenUp',
  'ArrowsArrowCircleBrokenUpLeft': 'ArrowCircleBrokenUpLeft',
  'ArrowsArrowCircleBrokenUpRight': 'ArrowCircleBrokenUpRight',
  'ArrowsArrowCircleDown': 'ArrowCircleDown',
  'ArrowsArrowCircleDownLeft': 'ArrowCircleDownLeft',
  'ArrowsArrowCircleDownRight': 'ArrowCircleDownRight',
  'ArrowsArrowCircleLeft': 'ArrowCircleLeft',
  'ArrowsArrowCircleRight': 'ArrowCircleRight',
  'ArrowsArrowCircleUp': 'ArrowCircleUp',
  'ArrowsArrowCircleUpLeft': 'ArrowCircleUpLeft',
  'ArrowsArrowCircleUpRight': 'ArrowCircleUpRight',
  'ArrowsArrowDown': 'ArrowDown',
  'ArrowsArrowDownLeft': 'ArrowDownLeft',
  'ArrowsArrowDownRight': 'ArrowDownRight',
  'ArrowsArrowLeft': 'ArrowLeft',
  'ArrowsArrowNarrowDown': 'ArrowNarrowDown',
  'ArrowsArrowNarrowDownLeft': 'ArrowNarrowDownLeft',
  'ArrowsArrowNarrowDownRight': 'ArrowNarrowDownRight',
  'ArrowsArrowNarrowLeft': 'ArrowNarrowLeft',
  'ArrowsArrowNarrowRight': 'ArrowNarrowRight',
  'ArrowsArrowNarrowUp': 'ArrowNarrowUp',
  'ArrowsArrowNarrowUpLeft': 'ArrowNarrowUpLeft',
  'ArrowsArrowNarrowUpRight': 'ArrowNarrowUpRight',
  'ArrowsArrowRight': 'ArrowRight',
  'ArrowsArrowsDown': 'ArrowsDown',
  'ArrowsArrowsLeft': 'ArrowsLeft',
  'ArrowsArrowSquareDown': 'ArrowSquareDown',
  'ArrowsArrowSquareDownLeft': 'ArrowSquareDownLeft',
  'ArrowsArrowSquareDownRight': 'ArrowSquareDownRight',
  'ArrowsArrowSquareLeft': 'ArrowSquareLeft',
  'ArrowsArrowSquareRight': 'ArrowSquareRight',
  'ArrowsArrowSquareUp': 'ArrowSquareUp',
  'ArrowsArrowSquareUpLeft': 'ArrowSquareUpLeft',
  'ArrowsArrowSquareUpRight': 'ArrowSquareUpRight',
  'ArrowsArrowsRight': 'ArrowsRight',
  'ArrowsArrowsTriangle': 'ArrowsTriangle',
  'ArrowsArrowsUp': 'ArrowsUp',
  'ArrowsArrowUp': 'ArrowUp',
  'ArrowsArrowUpLeft': 'ArrowUpLeft',
  'ArrowsArrowUpRight': 'ArrowUpRight',
  'ChartsBarChart01': 'BarChart01',
  'ChartsBarChart02': 'BarChart02',
  'ChartsBarChart03': 'BarChart03',
  'ChartsBarChart04': 'BarChart04',
  'ChartsBarChart05': 'BarChart05',
  'ChartsBarChart06': 'BarChart06',
  'ChartsBarChart07': 'BarChart07',
  'ChartsBarChart08': 'BarChart08',
  'ChartsBarChart09': 'BarChart09',
  'ChartsBarChart10': 'BarChart10',
  'ChartsBarChart11': 'BarChart11',
  'ChartsBarChart12': 'BarChart12',
  'ChartsBarChartCircle01': 'BarChartCircle01',
  'ChartsBarChartCircle02': 'BarChartCircle02',
  'ChartsBarChartCircle03': 'BarChartCircle03',
  'ChartsBarChartSquare01': 'BarChartSquare01',
  'ChartsBarChartSquare02': 'BarChartSquare02',
  'ChartsBarChartSquare03': 'BarChartSquare03',
  'ChartsBarChartSquareDown': 'BarChartSquareDown',
  'ChartsBarChartSquareMinus': 'BarChartSquareMinus',
  'ChartsBarChartSquarePlus': 'BarChartSquarePlus',
  'ChartsBarChartSquareUp': 'BarChartSquareUp',
  'ChartsBarLineChart': 'BarLineChart',
  'AlertsBell01': 'Bell01',
  'AlertsBell02': 'Bell02',
  'AlertsBell03': 'Bell03',
  'AlertsBell04': 'Bell04',
  'AlertsBellMinus': 'BellMinus',
  'AlertsBellOff01': 'BellOff01',
  'AlertsBellOff02': 'BellOff02',
  'AlertsBellOff03': 'BellOff03',
  'AlertsBellPlus': 'BellPlus',
  'AlertsBellRinging01': 'BellRinging01',
  'AlertsBellRinging02': 'BellRinging02',
  'AlertsBellRinging03': 'BellRinging03',
  'AlertsBellRinging04': 'BellRinging04',
  'AqProductsCalibration': 'Calibration',
  'ChartsChartBreakoutCircle': 'ChartBreakoutCircle',
  'ChartsChartBreakoutSquare': 'ChartBreakoutSquare',
  'ArrowsChevronDown': 'ChevronDown',
  'ArrowsChevronDownDouble': 'ChevronDownDouble',
  'ArrowsChevronLeft': 'ChevronLeft',
  'ArrowsChevronLeftDouble': 'ChevronLeftDouble',
  'ArrowsChevronRight': 'ChevronRight',
  'ArrowsChevronRightDouble': 'ChevronRightDouble',
  'ArrowsChevronSelectorHorizontal': 'ChevronSelectorHorizontal',
  'ArrowsChevronSelectorVertical': 'ChevronSelectorVertical',
  'ArrowsChevronUp': 'ChevronUp',
  'ArrowsChevronUpDouble': 'ChevronUpDouble',
  'AqProductsCollocation': 'Collocation',
  'ArrowsCornerDownLeft': 'CornerDownLeft',
  'ArrowsCornerDownRight': 'CornerDownRight',
  'ArrowsCornerLeftDown': 'CornerLeftDown',
  'ArrowsCornerLeftUp': 'CornerLeftUp',
  'ArrowsCornerRightDown': 'CornerRightDown',
  'ArrowsCornerRightUp': 'CornerRightUp',
  'ArrowsCornerUpLeft': 'CornerUpLeft',
  'ArrowsCornerUpRight': 'CornerUpRight',
  'ArrowsExpand01': 'Expand01',
  'ArrowsExpand02': 'Expand02',
  'ArrowsExpand03': 'Expand03',
  'ArrowsExpand04': 'Expand04',
  'ArrowsExpand05': 'Expand05',
  'ArrowsExpand06': 'Expand06',
  'ArrowsFlipBackward': 'FlipBackward',
  'ArrowsFlipForward': 'FlipForward',
  'ChartsHorizontalBarChart01': 'HorizontalBarChart01',
  'ChartsHorizontalBarChart02': 'HorizontalBarChart02',
  'ChartsHorizontalBarChart03': 'HorizontalBarChart03',
  'CommunicationInbox01': 'Inbox01',
  'CommunicationInbox02': 'Inbox02',
  'ArrowsInfinity': 'Infinity',
  'ChartsLineChartDown01': 'LineChartDown01',
  'ChartsLineChartDown02': 'LineChartDown02',
  'ChartsLineChartDown03': 'LineChartDown03',
  'ChartsLineChartDown04': 'LineChartDown04',
  'ChartsLineChartDown05': 'LineChartDown05',
  'ChartsLineChartUp01': 'LineChartUp01',
  'ChartsLineChartUp02': 'LineChartUp02',
  'ChartsLineChartUp03': 'LineChartUp03',
  'ChartsLineChartUp04': 'LineChartUp04',
  'ChartsLineChartUp05': 'LineChartUp05',
  'CommunicationMail01': 'Mail01',
  'CommunicationMail02': 'Mail02',
  'CommunicationMail03': 'Mail03',
  'CommunicationMail04': 'Mail04',
  'CommunicationMail05': 'Mail05',
  'CommunicationMessageAlertCircle': 'MessageAlertCircle',
  'CommunicationMessageAlertSquare': 'MessageAlertSquare',
  'CommunicationMessageChatCircle': 'MessageChatCircle',
  'CommunicationMessageChatSquare': 'MessageChatSquare',
  'CommunicationMessageCheckCircle': 'MessageCheckCircle',
  'CommunicationMessageCheckSquare': 'MessageCheckSquare',
  'CommunicationMessageCircle01': 'MessageCircle01',
  'CommunicationMessageCircle02': 'MessageCircle02',
  'CommunicationMessageDotsCircle': 'MessageDotsCircle',
  'CommunicationMessageDotsSquare': 'MessageDotsSquare',
  'CommunicationMessageHeartCircle': 'MessageHeartCircle',
  'CommunicationMessageHeartSquare': 'MessageHeartSquare',
  'CommunicationMessageNotificationCircle': 'MessageNotificationCircle',
  'AlertsMessageNotificationSquare': 'MessageNotificationSquare',
  'CommunicationMessageNotificationSquare': 'MessageNotificationSquare',
  'CommunicationMessagePlusCircle': 'MessagePlusCircle',
  'CommunicationMessagePlusSquare': 'MessagePlusSquare',
  'CommunicationMessageQuestionCircle': 'MessageQuestionCircle',
  'CommunicationMessageQuestionSquare': 'MessageQuestionSquare',
  'CommunicationMessageSmileCircle': 'MessageSmileCircle',
  'CommunicationMessageSmileSquare': 'MessageSmileSquare',
  'CommunicationMessageSquare01': 'MessageSquare01',
  'CommunicationMessageSquare02': 'MessageSquare02',
  'CommunicationMessageTextCircle01': 'MessageTextCircle01',
  'CommunicationMessageTextCircle02': 'MessageTextCircle02',
  'CommunicationMessageTextSquare01': 'MessageTextSquare01',
  'CommunicationMessageTextSquare02': 'MessageTextSquare02',
  'CommunicationMessageXCircle': 'MessageXCircle',
  'CommunicationMessageXSquare': 'MessageXSquare',
  'AqProductsMonitor': 'Monitor',
  'AlertsNotificationBox': 'NotificationBox',
  'AlertsNotificationText': 'NotificationText',
  'CommunicationPhone': 'Phone',
  'CommunicationPhoneCall01': 'PhoneCall01',
  'CommunicationPhoneCall02': 'PhoneCall02',
  'CommunicationPhoneHangUp': 'PhoneHangUp',
  'CommunicationPhoneIncoming01': 'PhoneIncoming01',
  'CommunicationPhoneIncoming02': 'PhoneIncoming02',
  'CommunicationPhoneOutgoing01': 'PhoneOutgoing01',
  'CommunicationPhoneOutgoing02': 'PhoneOutgoing02',
  'CommunicationPhonePause': 'PhonePause',
  'CommunicationPhonePlus': 'PhonePlus',
  'CommunicationPhoneX': 'PhoneX',
  'ChartsPieChart01': 'PieChart01',
  'ChartsPieChart02': 'PieChart02',
  'ChartsPieChart03': 'PieChart03',
  'ChartsPieChart04': 'PieChart04',
  'ChartsPresentationChart01': 'PresentationChart01',
  'ChartsPresentationChart02': 'PresentationChart02',
  'ChartsPresentationChart03': 'PresentationChart03',
  'ArrowsRefreshCcw01': 'RefreshCcw01',
  'ArrowsRefreshCcw02': 'RefreshCcw02',
  'ArrowsRefreshCcw03': 'RefreshCcw03',
  'ArrowsRefreshCcw04': 'RefreshCcw04',
  'ArrowsRefreshCcw05': 'RefreshCcw05',
  'ArrowsRefreshCw01': 'RefreshCw01',
  'ArrowsRefreshCw02': 'RefreshCw02',
  'ArrowsRefreshCw03': 'RefreshCw03',
  'ArrowsRefreshCw04': 'RefreshCw04',
  'ArrowsRefreshCw05': 'RefreshCw05',
  'ArrowsReverseLeft': 'ReverseLeft',
  'ArrowsReverseRight': 'ReverseRight',
  'CommunicationSend01': 'Send01',
  'CommunicationSend02': 'Send02',
  'CommunicationSend03': 'Send03',
  'AqProductsSites': 'Sites',
  'ArrowsSwitchHorizontal01': 'SwitchHorizontal01',
  'ArrowsSwitchHorizontal02': 'SwitchHorizontal02',
  'ArrowsSwitchVertical01': 'SwitchVertical01',
  'ArrowsSwitchVertical02': 'SwitchVertical02',
  'AlertsThumbsDown': 'ThumbsDown',
  'AlertsThumbsUp': 'ThumbsUp',
  'ChartsTrendDown01': 'TrendDown01',
  'ChartsTrendDown02': 'TrendDown02',
  'ChartsTrendUp01': 'TrendUp01',
  'ChartsTrendUp02': 'TrendUp02'
};
