// Auto-generated barrel exports for all icons
typedef import('@airqo-icons/core').IconMeta IconMeta;
import { icons } from '@airqo-icons/core';

// Dynamically re-export each React component
// This file is generated by scripts/generate-icons.js

// Begin icons export
${'' /* placeholder - actual exports injected by generate-icons */}
// End icons export