name: airqo_icons
description: AirQo icon library for Flutter
version: 0.1.0
publish_to: 'none' # Remove to publish publicly
environment:
  sdk: '>=2.17.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3

dev_dependencies:
  build_runner: ^2.3.3
  svg_to_flutter: ^0.1.0 # hypothetical plugin to convert svgs