# .github/workflows/preview-website.yml
name: Preview Documentation Website

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'website/**'
      - 'svgs/**'
      - 'packages/core/**'
      - 'packages/react/**'
      - '.github/workflows/preview-website.yml'

jobs:
  preview:
    name: Build Preview
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8.10.0
          run_install: false

      # Explicitly set shell environment variable
      - name: Set shell environment
        run: echo "SHELL=/bin/bash" >> $GITHUB_ENV

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup PNPM cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Generate Icons
        run: pnpm generate

      - name: Fix component types
        run: pnpm fix-component-types

      - name: Enhance React Native Icons
        run: pnpm enhance-rn

      - name: Build website
        working-directory: ./website
        run: |
          echo "Building website preview..."
          pnpm build

      - name: Upload website build artifact
        uses: actions/upload-artifact@v3
        with:
          name: website-preview
          path: ./website/out
          retention-days: 7

      - name: Add PR comment with preview info
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = context.issue.number;

            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: `🚀 **Website Preview Build Complete**

            The website preview for this PR has been built successfully! 

            You can download the preview artifact from the GitHub Actions tab to test the changes locally.

            *This is an automated message from the Preview Website workflow.*`
            });

      - name: PR Summary
        run: |
          echo "### Website Preview Build Complete ✅" >> $GITHUB_STEP_SUMMARY
          echo "📦 Preview artifact has been uploaded and can be downloaded from the GitHub Actions tab." >> $GITHUB_STEP_SUMMARY
          echo "📡 PR #${{ github.event.pull_request.number }} by @${{ github.event.pull_request.user.login }}" >> $GITHUB_STEP_SUMMARY
