name: CI & Release
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Create output directories
        run: |
          mkdir -p packages/react/src/icons
          mkdir -p packages/react-native/src/icons
          mkdir -p packages/flutter/assets
          mkdir -p packages/vue/src/icons
          mkdir -p packages/core/src

      - name: Build packages
        run: |
          pnpm run optimize
          node scripts/generate-icons.js
          pnpm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            packages/*/dist
            packages/*/package.json

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          scope: '@airqo-icons-min'

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: packages

      - name: Configure Git User
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Install dependencies
        run: pnpm install

      - name: Setup NPM token in package directories
        run: |
          for pkg in core react react-native vue; do
            echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > "packages/$pkg/.npmrc"
            echo "registry=https://registry.npmjs.org/" >> "packages/$pkg/.npmrc"
            echo "@airqo-icons-min:registry=https://registry.npmjs.org/" >> "packages/$pkg/.npmrc"
            echo "access=public" >> "packages/$pkg/.npmrc"
            chmod 0600 "packages/$pkg/.npmrc"
          done

      - name: Verify NPM Authentication
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release --debug

      - name: Manual Package Publishing
        if: failure()
        run: |
          echo "Attempting manual package publishing..."
          for pkg in core react react-native vue; do
            cd "packages/$pkg"
            echo "Publishing @airqo-icons-min/$pkg..."
            npm publish --access public || echo "$pkg package publish failed"
            cd ../..
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Debug Publishing (if failure)
        if: failure()
        run: |
          echo "=== Release failed, showing diagnostic information ==="
          echo "Current working directory: $(pwd)"
          echo "=== NPM whoami:"
          npm whoami || echo "Not logged in to NPM"
          echo "=== Package versions:"
          for pkg in core react react-native vue; do
            echo "=== @airqo-icons-min/$pkg ===="
            echo "package.json contents:"
            cat "packages/$pkg/package.json"
            echo ".npmrc contents:"
            cat "packages/$pkg/.npmrc" | sed 's/:.*/: ***/'
          done
