name: CI & Release
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 7 # <-- must match your lockfileVersion in pnpm-lock.yaml
          run_install: false # <-- we'll install manually below

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ${{ env.PNPM_STORE_PATH }}
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: pnpm-store-${{ runner.os }}-

      - name: Get pnpm store directory
        run: echo "PNPM_STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          pnpm install --frozen-lockfile --lockfile-dir=.
          pnpm list -r

      - name: Optimize SVGs
        run: pnpm run optimize

      - name: Generate Icons
        run: pnpm run generate

      - name: Build All Packages
        run: pnpm run build

      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 7
          run_install: false

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ${{ env.PNPM_STORE_PATH }}
          key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: pnpm-store-${{ runner.os }}-

      - name: Get pnpm store directory
        run: echo "PNPM_STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          pnpm install --frozen-lockfile --lockfile-dir=.
          pnpm list -r

      - name: Run Semantic Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUB_DEV_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}
        run: npx semantic-release

      - name: Setup Flutter SDK for publish
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'

      - name: Publish Flutter package to pub.dev
        if: env.PUB_DEV_TOKEN != ''
        env:
          PUB_DEV_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}
        run: |
          cd packages/flutter
          flutter pub get
          mkdir -p ~/.pub-cache
          echo '{"https://pub.dev":{"token":"'$PUB_DEV_TOKEN'"}}' > ~/.pub-cache/credentials.json
          flutter pub publish --force
