name: CI & Release
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Optimize SVGs
        run: pnpm run optimize
      - name: Generate Icons
        run: pnpm run generate
      - name: Build All Packages
        run: pnpm run build
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'
  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Semantic Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUB_DEV_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}
        run: npx semantic-release
      - name: Setup Flutter SDK for publish
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'
      - name: Publish Flutter package to pub.dev
        if: env.PUB_DEV_TOKEN != ''
        env:
          PUB_DEV_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}
        run: |
          cd packages/flutter
          flutter pub get
          mkdir -p ~/.pub-cache
          echo '{"https://pub.dev":{"token":"'$PUB_DEV_TOKEN'"}}' > ~/.pub-cache/credentials.json
          flutter pub publish --force